### ISSUE TITLE
Segfault GLXBadFBConfig

### ISSUE THREAD

**Issue by jeng** [retifrav/sdl-imgui-example#1]
A null check is missing for the result from `SDL_GL_CreateContext`.  This was causing Glad to segfault when attempting to get the GL_VERSION.  

Adding the following conditional allowed me to locate the issue which was reported as `GLXBadFBConfig`.  On my older laptop I needed to roll back the gl version defined for linux to fix it.

 ```
    SDL_GLContext gl_context = SDL_GL_CreateContext(window);
    if (gl_context == NULL){
        std::cerr << "[ERROR] Failed to get a GL Context" << std::endl;
        std::cerr << SDL_GetError() << std::endl;
        return -1;
    }
```

**Comment by retifrav** [comment]
That's a sad overlook, thank you for reporting.
